
var cubes = [
    {
        made: false,
        x: 1280,
        y: 1400,
        offset: 100,
        radius: 990,
        visible: true
    },
    {
        made: false,
        x: 400,
        y: 400,
        offset: 100,
        radius: 45,
        angleOffset: 0,
        radiusOffset: 45,
        row: 1,
        col: 22,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 0,
        radiusOffset: 135,
        row: 2,
        col: 21,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 0,
        radiusOffset: 225,
        row: 3,
        col: 20,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 0,
        radiusOffset: 315,
        row: 4,
        col: 19,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 0,
        radiusOffset: 405,
        row: 5,
        col: 18,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 0,
        radiusOffset: 495,
        row: 6,
        col: 17,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 0,
        radiusOffset: 585,
        row: 7,
        col: 16,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 0,
        radiusOffset: 675,
        row: 8,
        col: 15,
        angleRefrence: 1,
        visible: false
    },

    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 0,
        radiusOffset: 765,
        row: 9,
        col: 14,
        angleRefrence: 1,
        visible: false
    },

    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 0,
        radiusOffset: 855,
        row: 10,
        col: 13,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 0,
        radiusOffset: 945,
        row: 11,
        col: 12,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 0,
        radiusOffset: 1035,
        row: 12,
        col: 11,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 0,
        radiusOffset: 1125,
        row: 13,
        col: 10,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 0,
        radiusOffset: 1215,
        row: 14,
        col: 9,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 0,
        radiusOffset: 1305,
        row: 15,
        col: 8,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 0,
        radiusOffset: 1395,
        row: 16,
        col: 7,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 0,
        radiusOffset: 1485,
        row: 17,
        col: 6,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 0,
        radiusOffset: 1575,
        row: 18,
        col: 5,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 0,
        radiusOffset: 1665,
        row: 19,
        col: 4,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 0,
        radiusOffset: 1755,
        row: 20,
        col: 3,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 0,
        radiusOffset: 1845,
        row: 21,
        col: 2,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 0,
        radiusOffset: 1935,
        row: 22,
        col: 1,
        angleRefrence: 1,
        visible: false
    },






    {
        made: false,
        x: 400,
        y: 400,
        offset: 100,
        radius: 45,
        angleOffset: 270,
        radiusOffset: 45,
        row: 22,
        col: 22,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 270,
        radiusOffset: 135,
        row: 21,
        col: 21,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 270,
        radiusOffset: 225,
        row: 20,
        col: 20,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 270,
        radiusOffset: 315,
        row: 19,
        col: 19,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 270,
        radiusOffset: 405,
        row: 18,
        col: 18,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 270,
        radiusOffset: 495,
        row: 17,
        col: 17,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 270,
        radiusOffset: 585,
        row: 16,
        col: 16,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 270,
        radiusOffset: 675,
        row: 15,
        col: 15,
        angleRefrence: 1,
        visible: false
    },

    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 270,
        radiusOffset: 765,
        row: 14,
        col: 14,
        angleRefrence: 1,
        visible: false
    },

    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 270,
        radiusOffset: 855,
        row: 13,
        col: 13,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 270,
        radiusOffset: 945,
        row: 12,
        col: 12,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 270,
        radiusOffset: 1035,
        row: 11,
        col: 11,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 270,
        radiusOffset: 1125,
        row: 10,
        col: 10,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 270,
        radiusOffset: 1215,
        row: 9,
        col: 9,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 270,
        radiusOffset: 1305,
        row: 8,
        col: 8,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 270,
        radiusOffset: 1395,
        row: 7,
        col: 7,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 270,
        radiusOffset: 1485,
        row: 6,
        col: 6,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 270,
        radiusOffset: 1575,
        row: 5,
        col: 5,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 270,
        radiusOffset: 1665,
        row: 4,
        col: 4,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 270,
        radiusOffset: 1755,
        row: 3,
        col: 3,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 270,
        radiusOffset: 1845,
        row: 2,
        col: 2,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 270,
        radiusOffset: 1935,
        row: 1,
        col: 1,
        angleRefrence: 1,
        visible: false
    },

    //diagonal y=-1x-1
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 272.9,
        radiusOffset: 1891,
        row: 2,
        col: 1,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 273.2,
        radiusOffset: 1801,
        row: 3,
        col: 2,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 273.6,
        radiusOffset: 1711,
        row: 4,
        col: 3,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 274.1,
        radiusOffset: 1621,
        row: 5,
        col: 4,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 274,
        radiusOffset: 1621,
        row: 6,
        col: 5,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 274.8,
        radiusOffset: 1531,
        row: 7,
        col: 6,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 275.7,
        radiusOffset: 1441,
        row: 8,
        col: 7,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 276.9,
        radiusOffset: 1351,
        row: 9,
        col: 8,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 279.4,
        radiusOffset: 1264,
        row: 10,
        col: 9,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 284,
        radiusOffset: 1176,
        row: 11,
        col: 10,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 296,
        radiusOffset: 1091,
        row: 12,
        col: 11,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 272.9 - 180,
        radiusOffset: 1891,
        row: 21,
        col: 22,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 273.2 - 180,
        radiusOffset: 1801,
        row: 20,
        col: 21,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 273.6 - 180,
        radiusOffset: 1711,
        row: 19,
        col: 20,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 274.1 - 180,
        radiusOffset: 1621,
        row: 18,
        col: 19,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 274 - 180,
        radiusOffset: 1621,
        row: 17,
        col: 18,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 274.8 - 180,
        radiusOffset: 1531,
        row: 16,
        col: 17,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 275.7 - 180,
        radiusOffset: 1441,
        row: 15,
        col: 16,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 276.9 - 180,
        radiusOffset: 1351,
        row: 14,
        col: 15,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 279.4 - 180,
        radiusOffset: 1264,
        row: 14,
        col: 15,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 284 - 180,
        radiusOffset: 1176,
        row: 13,
        col: 14,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 296 - 180,
        radiusOffset: 1091,
        row: 12,
        col: 13,
        angleRefrence: 1,
        visible: false
    },
    //diagonal y=x+1       ////////////////////////////////////////////////////////////////////////////////////////////////////////- DO ROWS AND COLOMNS
    {
        made: false,
        x: 600,
        y: 2260,
        offset: 100,
        radius: 45,
        angleOffset: 272.9 - 90,
        radiusOffset: 1891,
        row: 1,
        col: 21,
        angleRefrence: 1,
        visible: false
    }, 
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 273.2 - 90,
        radiusOffset: 1801,
        row: 2,
        col: 20,
        angleRefrence: 1,
        visible: false
    }, 
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 273.6 - 90,
        radiusOffset: 1711,
        row: 3,
        col: 19,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 274.1 - 90,
        radiusOffset: 1621,
        row: 4,
        col: 18,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 274 - 90,
        radiusOffset: 1621,
        row: 5,
        col: 17,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 274.8 - 90,
        radiusOffset: 1531,
        row: 6,
        col: 16,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 275.7 - 90,
        radiusOffset: 1441,
        row: 7,
        col: 15,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 276.9 - 90,
        radiusOffset: 1351,
        row: 8,
        col: 16,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 279.4 - 90,
        radiusOffset: 1264,
        row: 9,
        col: 15,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 284 - 90,
        radiusOffset: 1176,
        row: 10,
        col: 14,
        angleRefrence: 1,
        visible: false
    }, 
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 296 - 90,
        radiusOffset: 1091,
        row: 11,
        col: 13,
        angleRefrence: 1,
        visible: false
    },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 272.9 - 270,
        radiusOffset: 1891,
        row: 22,
        col: 12,
        angleRefrence: 1,
        visible: false
    }, 
    /////////////////////////////////////////////////////////////start here
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 273.2 - 270,
        radiusOffset: 1801,
        row: 13,
        col: 11,
        angleRefrence: 1,
        visible: false
    },
     {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 273.6 - 270,
        radiusOffset: 1711,
        row: 14,
        col: 10,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 274.1 - 270,
        radiusOffset: 1621,
        row: 15,
        col: 9,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 274 - 270,
        radiusOffset: 1621,
        row: 16,
        col: 8,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 274.8 - 270,
        radiusOffset: 1531,
        row: 17,
        col: 7,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 275.7 - 270,
        radiusOffset: 1441,
        row: 18,
        col: 6,
        angleRefrence: 1,
        visible: false
    },
     {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 276.9 - 270,
        radiusOffset: 1351,
        row: 19,
        col: 5,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 279.4 - 270,
        radiusOffset: 1264,
        row: 20,
        col: 4,
        angleRefrence: 1,
        visible: false
    }, 
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: 284 - 270,
        radiusOffset: 1176,
        row: 21,
        col: 3,
        angleRefrence: 1,
        visible: false
     }, 
        {
            made: false,
            x: 600,
            y: 2560,
            offset: 100,
            radius: 45,
            angleOffset: 296 - 270,
            radiusOffset: 1091,
            row: 22,
            col: 2,
            angleRefrence: 1,
            visible: false
        },
    {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: (272.9 - 270) * -1,
        radiusOffset: 1891,
        row: 2,
        col: 1,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: (273.2 - 270) * -1,
        radiusOffset: 1801,
        row: 3,
        col: 2,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: (273.6 - 270) * -1,
        radiusOffset: 1711,
        row: 4,
        col: 3,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: (274.1 - 270) * -1,
        radiusOffset: 1621,
        row: 5,
        col: 4,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: (274 - 270) * -1,
        radiusOffset: 1621,
        row: 6,
        col: 5,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: (274.8 - 270) * -1,
        radiusOffset: 1531,
        row: 7,
        col: 6,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: (275.7 - 270) * -1,
        radiusOffset: 1441,
        row: 8,
        col: 7,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: (276.9 - 270) * -1,
        radiusOffset: 1351,
        row: 9,
        col: 8,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: (279.4 - 270) * -1,
        radiusOffset: 1264,
        row: 10,
        col: 9,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: (284 - 270) * -1,
        radiusOffset: 1176,
        row: 11,
        col: 10,
        angleRefrence: 1,
        visible: false
    }, {
        made: false,
        x: 600,
        y: 2560,
        offset: 100,
        radius: 45,
        angleOffset: (296 - 270) * -1,
        radiusOffset: 1091,
        row: 12,
        col: 11,
        angleRefrence: 1,
        visible: false
    },
];
